---
abstract: 'Reverse HTTP Proxy'
author:
  - 'Brian Medley <bpmedley@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-rhttp
requires:
  AnyEvent: 0
  IO::String: 0
  JSON::PP: 0
version: 0.01
